version: "3"
services:
  ai-object-counter:
    build: .
    ports:
      - 8079:8081
    environment:
      - "MariaDBHost=db"
      - "MariaDBPort=3306"
      - "MariaDBUsername=root"
      - "MariaDBPassword=notSecureChangeMe"
      - "MariaDBDatabase=ai-people-counter"
    networks:
      - int
    depends_on:
      - db

  db:
    image: mariadb:11.4.1-rc
    ports:
      - 3369:3306
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=notSecureChangeMe"
    networks:
      - int

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8078:80
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_USER=root"
      - "PMA_PASSWORD=notSecureChangeMe"
      - "PMA_HOST=db"
    networks:
      - int

networks:
  int: