version: "3"
services:
  ai-object-counter:
    build: .
    ports:
      - 8079:8081
    environment:
      - MariaDBHost=db
      - MariaDBUsername=root
      - MariaDBPassword=notSecureChangeMe
      - MariaDBDatabase=ai-people-counter
    networks:
      - int

  db:
    image: mariadb:11.4.1-rc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    networks:
      - int

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8078:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=notSecureChangeMe
      - PMA_HOST=db
    networks:
      - int

networks:
  int: